name: stash Go CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ['1.18']

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Use Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run test
        run: make test-cover

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
